GetError: Fetches all necessary error and counts to help planning support in creating report. It also detects automatically if today is monday so it will gather necessary information over the weekend.